### PR TITLE
Adds viewComments option to disable markdown under chessboard

### LINKED ISSUE #5: [Feature request] Add option to disable the markdown are under the chess board
First of thanks for the awesome plugin. Really useful because unlike other plugins I can scroll through the moves. Also because PGN is a lot easier for humans than FEN.

However I notice that I rarely use the block of markdown area under the chess board so it takes up space for nothing. I would love to be able to disable it with an option in the code block. Or disable it in the default options and enable it only for the chess studies where I need one.

### PR DESCRIPTION
**Pull request by latenitecoding**
Resolves #5

### CODE REVIEW

**Comment by chrislicodes** [comment]
Thanks for the PR, I will check it out tomorrow.

**Comment by latenitecoding** [comment]
My apologies! I meant to split the PR. I just added FEN support to resolve #7 though. I wasn't sure if you had ideas about how you wanted to approach FEN positions. I noticed that you're using the chess.js API which already supports FEN. I also noticed that you're saving the PGN to a .json file. It seems to me that trying to save the FEN locally introduces too many complications. Instead, I added a FEN setting that can store the FEN string. I also modified the Chess command to accept FEN or PGN in the text area. PGN's can't include the '/' character and all FEN must include the '/' character, so it's pretty easy to differentiate between the two. The neat thing is that now someone can use the FEN to put in a start position and then use the PGN support to add moves on top of that position. The downside is that if they delete the FEN field or change it, they could crash the board unless a free mode is enabled.

**Comment by latenitecoding** [comment]
Moving fen support to its own PR

**Comment by latenitecoding** [comment]
I went ahead and squashed the commits. Let me know when this gets merged in. Then I can rebase the other PRs.

**Comment by chrislicodes** [comment]
Sure! I have limited access to my laptop at the moment but I will have time this week to bring this project up to date

**Comment by latenitecoding** [comment]
> Sure! I have limited access to my laptop at the moment but I will have time this week to bring this project up to date

Sounds great! No worries. I was also a bit sloppy in putting these PRs together originally. They should be much better organized now and easy to review. I also maintain a dev branch on my own fork that has all the PRs together. I've been using it inside of Obsidian. It's been working pretty well so far outside of the bug I mentioned when you draw on a board with no moves.

I don't have a ton of experience with the other chess plugins, but it seems like these updates should put you over the top in terms of chess support. If we could use this plugin to draw on an initial board, I think you'd have the most feature rich chess plugin on Obsidian.

**Comment by latenitecoding** [comment]
> Sure! I have limited access to my laptop at the moment but I will have time this week to bring this project up to date

What do you need to get this merged in? I don't mean to bug you if you're on vacation. I was just curious. I have several additional features other than the three PRs that I've already sent you. I don't mind meeting virtually sometime to get these merged in if that's what we need to do.

**Pull request merged**
